
PF= \
	.dbe.pf \
	dbgenloc_default.pf \
	orbgenloc.pf \
	dbloc2.pf \
	dbloc_map.pf \
	smartpick_classic.pf \
	tkdbpick.pf \
	dbcentral.pf \
	dbbuild.pf \
	aeic_dbevents.pf  \
	dbfixids.pf  \
	elog.pf \
	dlmon.pf \
	trdefaults.pf

include $(AEICMAKE)
