DATADIR=tables/genloc/tt1dcvl
DATA= \
	gulfak.pf \
	northak.pf \
	pav_dut.pf \
	red_ili.pf \
	scak.pf \
	augustine.pf

# suspend DEST assignment to put files directly in $ANTELOPE
include $(AEICMAKE)
