DATADIR=tables/genloc/ttlvz
DATA= \
	augustine.pf \
	gulfak.pf \
	kilauea_hg50.pf \
	northak.pf \
	pav_dut.pf \
	red_ili.pf \
	scak.pf

# suspend DEST assignment to put files directly in $ANTELOPE
include $(AEICMAKE)
