DATADIR=maps
DATA= \
	aeic.bp \
	aeic_vol.bp \
	circle_descr.bp \
	figure1.bp \
	\
	Clear_mapset_macro.pf \
	landscape_gray_mapset_macro.pf \
	landscape_mapset_macro.pf \
	southc5_gray_mapset_macro.pf \
	southc5_mapset_macro.pf \
	southc_mapset_macro.pf \
	volc_basemap_1_mapset_macro.pf \
	\
	ak_dbmapevents.pf \
	dbmap_release.pf \
	dbmapevents.pf \
	\
	country.label \
	faults.label \
	oceans.label \
	pipeline.label \
	volcanoes.label \
	volcanoes_cool.label \
	volcanoes_lots.label \
	\
	bath.lin \
	faults.lin \
	faults.lin.new \
	pipeline.lin \
	\
	aleut_cities.dat \
	cities.dat \
	pipepumps.dat


include $(AEICMAKE)
